### ISSUE TITLE
How to training on android device?

### ISSUE THREAD

**Issue by jinzequn** [doc-ai/tensorio#15]
Is there any example to training on android devices?

**Comment by phildow** [comment]
Hey @jinzequn , sorry I just noticed this! We haven't gotten training working on Android phones yet and have been prioritizing iOS support since that is the platform we primarily use. But we are hoping to bring full support for training on Android by the middle of this year.

**Comment by phildow** [comment]
Training on Android devices is now possible: 
https://github.com/doc-ai/tensorio-android/releases/tag/0.9.12
