### ISSUE TITLE
On-device training on iOS

### ISSUE THREAD

**Issue by chrischen1104** [doc-ai/tensorio#38]
Hi! I'm new to Tensor/IO. I want to use tensor/IO for on-device training on iOS. May I know if you have instructions for it? The example folder doesn't seem to be for on-device training?

**Comment by phildow** [comment]
Hi @chrischen1104, the example folder does contain code for training on device. Have a look at any of the four test files and in each one you'll find an `testModel_EstimatorTrain` test that trains one of the included models.
